name: dart_sdk
description: glide client sdk
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  dio: ^4.0.6
  analyzer: ^4.2.0
  rxdart: ^0.27.4
  # retrofit: ^3.0.1+1
  json_annotation: ^4.5.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  test: ^1.16.0
